@baseUrl = http://127.0.0.1:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10

### Lista apenas um recado

GET {{baseUrl}}/recados/2/

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "4Novo recado",
    "de": "Gabriel",
    "para": "Neusa"
}
### Atualiza um recado

PATCH {{baseUrl}}/recados/5/
Content-Type: application/json

{
    "lido": false,
    "texto": "testando atualização"
}

### Apaga um recado 
DELETE {{baseUrl}}/recados/4/




# PESSOAS
### Lista todos as Pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=10

### Lista apenas uma Pessoa

GET {{baseUrl}}/pessoas/2/

### Cria uma PEssoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "email1@email.com",
    "password": "123456",
    "nome": "Gabriel"
}