@baseUrl = http://127.0.0.1:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10

### Lista apenas um recado

GET {{baseUrl}}/recados/2/

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "4Novo recado",
    "de": "Gabriel",
    "para": "Neusa"
}
### Atualiza um recado

PATCH {{baseUrl}}/recados/3/
Content-Type: application/json

{
    "texto": "ATUALIZANDO O RECADO",
    "de": "Joao",
    "para": "Neusa"
}

### Apaga um recado 
DELETE {{baseUrl}}/recados/1/
