@baseUrl = http://127.0.0.1:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10

### Lista apenas um recado

GET {{baseUrl}}/recados/10/

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Gabriel esta enviando um recado para o Henrique",
    "deId": 12,
    "paraId": 13
}
### Atualiza um recado

PATCH {{baseUrl}}/recados/5/
Content-Type: application/json

{
    "lido": false,
    "texto": "testando atualização"
}

### Apaga um recado 
DELETE {{baseUrl}}/recados/4/




# PESSOAS
### Lista todos as Pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=10

### Lista apenas uma Pessoa

GET {{baseUrl}}/pessoas/8/

### Cria uma PEssoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "henri@email.com",
    "password": "123456",
    "nome": "Henrique Lourenco"
}

### Atualiza uma pessoa

PATCH {{baseUrl}}/pessoas/8/
Content-Type: application/json

{
    "password": "99999",
    "nome": "Henrique"
}

### Apaga uma pessoa 
DELETE {{baseUrl}}/pessoas/8/